### ISSUE TITLE
Doesn't compile on osx 12.6 Monterey.

### ISSUE THREAD

**Issue by alonsoir** [Mic92/cntr#150]
I have tried to compile with both ways and in both I get compilation errors.

[stacktrace cntr.txt](https://github.com/Mic92/cntr/files/9849915/stacktrace.cntr.txt)

**Comment by Mic92** [comment]
Sorry, but you cannot use cntr on macOS. It depends on many linux APIs by design.

**Comment by synek317** [comment]
Might be worth adding this to the readme.

**Comment by Mic92** [comment]
done in https://github.com/Mic92/cntr/pull/163
